name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/checkout@master
      with:
        # Private version of https://github.com/actions/hello-world-docker-action
        repository:  jaswantrock05/workshop-hello-gitops 
        #ref: refs/tags/v1
        token: ${{ secrets.GITHUB_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT to clone that private repo
    - name: Run a ls script
      run: |
        ls -la
          date > date.txt
          git config --local user.email "jaswantrock05@gmail.com"
          git config --local user.name "jaswantrock05"
          git add .
          git commit -m "generated"
          git push
          
