# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1.1.0
      with:
        repository: ${{ secrets.DOCKER_USERNAME }}/demo-app
        #image: jaswantrock05/demo-app
        tag: ${{ github.sha }}, latest
        registry: docker.io  
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
     # uses: jerray/publish-docker-action@master
     # with:
      #  repository: jaswantrock05/demo-app
      #  auto_tag: true
      #  tags: v1.1  
      #  allow_pull_request: true  
      #  registry: docker.pkg.github.com  
      #  username: ${{ secrets.DOCKER_USERNAME }}
      #  password: ${{ secrets.DOCKER_PASSWORD }}
    #- id: deploy
    #  env:
     #   NEW_VERSION: ${{ steps.build.outputs.tag }}
     # run: |
     #   docker pull $NEW_VERSION  
     
        
        
      
          
 
      
