name: My workflow
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout jaswantrock05/workshop-hello-gitops
        uses: actions/checkout@v2
        with:
          repository: jaswantrock05/workshop-hello-gitops
          ref: refs/heads/master
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: $
          persist-credentials: false
          path: ./.github/actions/awesome-action
      - uses: ./.github/actions/awesome-action
      - name: Last step
        run: ...
