name: Go     
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
        
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jaswantrock05/demo-app
        tag: ${{ secrets.TAG_VALUE }}
        registry: docker.io  
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Checkout GitHub Action Repo
      uses: actions/checkout@v2
      with:
        repository: jaswantrock05/workshop-hello-gitops 
        #ref: v0.1.2
        token: ${{ secrets.token }} # stored in GitHub secrets
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        repository: jaswantrock05/workshop-hello-gitops   
        find: "v1.18.3"
        replace: "v1.18.4"
        include: "app-deployment.yaml" # Will match all README.md files in any nested directory
    - name: Commit files
      run: |
        git config --local user.email "jaswantrock05@gmail.com"
        git config --local user.name "jaswantrock05"
        git commit -am "Bump docker tag"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: jaswantrock05/workshop-hello-gitops  
        branch: B778
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
